const treatments = [
  {
    type: 'טיפול בקבלה והתחייבות (ACT)',
    category: 'רגשי',
    length: 'קצר',
    homework: 'כן',
    description: 'מיועד לאנשים עם הפרעות חרדה ודיכאון, מתמקד בלמידה איך לקבל את המחשבות והרגשות בלי להילחם בהם.',
  },
  {
    type: 'טיפול בעזרת בעלי חיים ',
    category: 'רגשי',
    length: 'ארוך',
    homework: 'לא',
    description: 'מתאים לילדים ומבוגרים עם בעיות רגשיות או נפשיות, משתמש בחיות ליצירת קשר רגשי ושיפור בקשר החברתי.',
  },
  {
    type: 'טיפול באמנות',
    category: 'רגשי',
    length: 'ארוך',
    homework: 'לא',
    description: 'מיועד לאנשים מכל הגילאים לעיבוד רגשי דרך ביטוי אומנותי, מסייע בהתמודדות עם לחצים וחרדות.',
  },
  {
    type: 'טיפול בחשיפה',
    category: 'רגשי',
    length: 'קצר',
    homework: 'כן',
    description: 'מיועד לטיפול בחרדות ופוביות, עובד על חשיפה הדרגתית ובטוחה למקור הפחד.',
  },
  {
    type: 'Eye Movement Desensitization and Reprocessing (EMDR)',
    category: 'רגשי',
    length: 'קצר',
    homework: 'לא',
    description: 'מתמקד בטיפול ב-PTSD, משתמש בהנחיות עיניים לעיבוד טראומות.',
  },
  {
    type: 'טיפול קבוצתי',
    category: 'רגשי',
    length: 'ארוך',
    homework: 'כן',
    description: 'מתאים למגוון בעיות רגשיות, מעודד תמיכה חברתית ולמידה מחוויות של אחרים.',
  },
  {
    type: 'יוגה',
    category: 'nan',
    length: 'nan',
    homework: 'לא',
    description: 'מיועדת לשיפור בריאות הגוף והנפש, עוזרת בניהול מתח וחרדה דרך תרגול גופני ונפשי.',
  },
  {
    type: 'תוספי תזונה צמחיים',
    category: 'nan',
    length: 'nan',
    homework: 'לא',
    description: 'נועדו לשיפור הבריאות הכללית, מתמקדים באיזון תזונתי ותמיכה במערכת החיסונית.',
  },
  {
    type: 'טיפול במוסיקה',
    category: 'רגשי',
    length: 'ארוך',
    homework: 'לא',
    description: 'מתאים לכל הגילאים, עוזר להתמודד עם בעיות נפשיות ורגשיות דרך ביטוי מוזיקלי.',
  },
  {
    type: 'טיפול פסיכודינמי ',
    category: 'רגשי',
    length: 'ארוך',
    homework: 'לא',
    description: 'מתמקד בחקירת התודעה הלא מודעת לטיפול בבעיות נפשיות והתנהגותיות.',
  },
  {
    type: 'ייעוץ תזונתי',
    category: 'nan',
    length: 'nan',
    homework: 'כן',
    description: 'מיועד לשיפור הבריאות דרך תזונה מאוזנת, תוך מתן הדרכה אישית.',
  },
  {
    type: 'ריפוי בעיסוק',
    category: 'nan',
    length: 'nan',
    homework: 'כן',
    description: 'מסייע למטופלים לשפר יכולות פונקציונליות ולהתמודד עם מגבלות גופניות או נפשיות.',
  },
  {
    type: 'ארומתרפיה',
    category: 'nan',
    length: 'nan',
    homework: 'לא',
    description: 'שימוש בשמנים אתריים לשיפור מצב הרוח והרגעה, מתאים למטופלים עם לחץ וחרדה.',
  },
  {
    type: 'טיפול באור',
    category: 'nan',
    length: 'nan',
    homework: 'לא',
    description: 'מתמקד בטיפול בהפרעות שינה ודיכאון עונתי, עובד על חשיפה לאור מלאכותי.',
  },
  {
    type: 'טיפול בתנועה וריקוד',
    category: 'nan',
    length: 'nan',
    homework: 'לא',
    description: 'מיועד לשחרור טנזיות וקידום בריאות נפשית דרך ביטוי גופני.',
  },
  {
    type: 'טיפול מגע גוף נפש',
    category: 'nan',
    length: 'nan',
    homework: 'לא',
    description: 'מטפל בשילוב של טכניקות מגע עם עבודה רגשית, מתאים למטופלים עם טראומות ומתחים.',
  },
  {
    type: 'SE - חוויה סומתית',
    category: 'רגשי',
    length: 'nan',
    homework: 'לא',
    description: 'מתמקד בשחרור טראומה דרך תנועות גוף ותודעה גופנית.',
  },
  {
    type: 'דיקור סיני',
    category: 'nan',
    length: 'קצר',
    homework: 'לא',
    description: 'מיועד לטיפול במגוון בעיות גופניות ורגשיות דרך עידוד זרימת האנרגיה בגוף.',
  },
  {
    type: 'שיאצו',
    category: 'nan',
    length: 'nan',
    homework: 'לא',
    description: 'טכניקת מסאז' יפנית המתמקדת בלחיצות על נקודות רפואיות לשיפור הבריאות הכללית.',
  },
  {
    type: 'נטורופתיה',
    category: 'nan',
    length: 'nan',
    homework: 'לא',
    description: 'מתמקדת בטיפול טבעי והוליסטי, משלבת שימוש בצמחים ושיטות רפואיות טבעיות.',
  },
  {
    type: 'הומאופתיה',
    category: 'nan',
    length: 'nan',
    homework: 'לא',
    description: 'מבוססת על עיקרון הדילול והסימון, מיועדת לטיפול במחלות כרוניות ועוד.',
  },
  {
    type: 'אוסטאופתיה',
    category: 'nan',
    length: 'קצר',
    homework: 'לא',
    description: 'טיפול בבעיות שלד ומפרקים דרך מניפולציות גופניות.',
  },
  {
    type: 'רפלקסולוגיה',
    category: 'nan',
    length: 'ארוך',
    homework: 'לא',
    description: 'מסאז' שמתמקד בלחיצות בכפות הרגליים להשפעה על איברים ומערכות בגוף.',
  },
  {
    type: 'עיסוי רפואי הוליסטי',
    category: 'nan',
    length: 'קצר',
    homework: 'לא',
    description: 'משלב טכניקות עיסוי מגוונות לטיפול רפואי ושחרור שרירים.',
  },
  {
    type: 'טווינא',
    category: 'nan',
    length: 'nan',
    homework: 'לא',
    description: 'סוג של עיסוי סיני המתמקד בשיפור זרימת הצ'י והדם בגוף.',
  },
  {
    type: 'כירופרקטיקה',
    category: 'nan',
    length: 'קצר',
    homework: 'לא',
    description: 'מתמקדת בטיפול בבעיות של השלד והעמוד השדרי דרך תיקונים מניפולטיביים.',
  },
  {
    type: 'שיטת פלדנקרייז',
    category: 'nan',
    length: 'ארוך',
    homework: 'לא',
    description: 'מעודדת למידה מחודשת של תנועה לשיפור פונקציות גופניות ומנטליות.',
  },
  {
    type: 'ביופידבק',
    category: 'רגשי',
    length: 'קצר',
    homework: 'לא',
    description: 'מיועד ללימוד ניהול פונקציות גופניות דרך משוב ממוחשב.',
  },
  {
    type: 'עיסוי לימפטי (ניקוז לימפטי)',
    category: 'nan',
    length: 'nan',
    homework: 'לא',
    description: 'מתמקד בשחרור נוזלים מהגוף ותמיכה במערכת הלימפה.',
  },
  {
    type: 'שיטת פאולה',
    category: 'nan',
    length: 'nan',
    homework: 'לא',
    description: 'טיפול בתנועה לשיפור התנועתיות והגמישות של הגוף.',
  },
  {
    type: 'הומוטוקסיקולוגיה',
    category: 'nan',
    length: 'nan',
    homework: 'לא',
    description: 'עוסקת בניקוי רעלים מהגוף דרך שיטות הוליסטיות.',
  },
  {
    type: 'הדרכת הורים',
    category: 'רגשי',
    length: 'nan',
    homework: 'כן',
    description: 'מספקת כלים להורים לניהול יחסים והתמודדות עם אתגרי ההורות.',
  },
  {
    type: 'שיטת אלכסנדר',
    category: 'nan',
    length: 'קצר',
    homework: 'לא',
    description: 'מתמקדת בשיפור תנוחת הגוף והקלה על כאבים ולחצים גופניים.',
  },
  {
    type: 'דיקור סיני אנטי אייג'ינג',
    category: 'nan',
    length: 'קצר',
    homework: 'לא',
    description: 'מיועד להאטת תהליכי הזדקנות דרך דיקור בנקודות מפתח.',
  },
  {
    type: 'אבחון אוטיזם',
    category: 'nan',
    length: 'קצר',
    homework: 'לא',
    description: 'בדיקות לאיתור סימפטומים של אוטיזם בילדים ומתבגרים.',
  },
  {
    type: 'היפנוזה',
    category: 'רגשי',
    length: 'nan',
    homework: 'לא',
    description: 'משמשת להפחתת חרדה, למידה עצמית והתמודדות עם פחדים והרגלים רעים.',
  },
  {
    type: 'העצמה אישית',
    category: 'רגשי',
    length: 'nan',
    homework: 'לא',
    description: 'מתמקדת בפיתוח כישורים אישיים והתמודדות עם אתגרים חיים.',
  },
  {
    type: 'טיפול ב-OCD',
    category: 'רגשי',
    length: 'ארוך',
    homework: 'כן',
    description: 'מיועד לאנשים עם הפרעת טורדנות כפייתית, מתמקד בשליטה בטקסים.',
  },
  {
    type: 'טיפול באוטיזם',
    category: 'רגשי',
    length: 'ארוך',
    homework: 'כן',
    description: 'מיועד לילדים ומבוגרים עם אוטיזם, מתמקד בשיפור תקשורת והתנהגות.',
  },
  {
    type: 'טיפול בדרמה',
    category: 'רגשי',
    length: 'ארוך',
    homework: 'לא',
    description: 'משתמש בדרמה לעיבוד רגשי ופיתוח מיומנויות חברתיות.',
  },
  {
    type: 'טיפול התנהגותי דיאלקטי (DBT)',
    category: 'רגשי',
    length: 'nan',
    homework: 'כן',
    description: 'טיפול התנהגותי המתמקד בשליטה רגשית ומיתוג מחשבתי.',
  },
  {
    type: 'טיפול זוגי',
    category: 'רגשי',
    length: 'ארוך',
    homework: 'כן',
    description: 'מיועד לזוגות המעוניינים לשפר את הקשר הרומנטי והתקשורת ביניהם.',
  },
  {
    type: 'טיפול לקהילה הגאה',
    category: 'רגשי',
    length: 'nan',
    homework: 'כן',
    description: 'מותאם לצרכים של אנשים בקהילת ה-LGBTQ+, מתמקד בתמיכה רגשית וחברתית.',
  },
  {
    type: 'טיפול מיני',
    category: 'רגשי',
    length: 'nan',
    homework: 'כן',
    description: 'עוסק בבעיות וחרדות מיניות, מספק כלים לשיפור החיים המיניים.',
  },
  {
    type: ' טיפול הפרעות קשב וריכוז - ADHD',
    category: 'רגשי',
    length: 'nan',
    homework: 'לא',
    description: 'עוזר למי שסובלים מ-ADHD לשפר תשומת לב וריכוז.',
  },
  {
    type: 'טיפול משפחתי',
    category: 'רגשי',
    length: 'ארוך',
    homework: 'כן',
    description: 'מיועד לשיפור היחסים בתוך המשפחה ופתרון קונפליקטים.',
  },
  {
    type: 'קלינאות תקשורת',
    category: 'nan',
    length: 'קצר',
    homework: 'לא',
    description: 'מיועדת לשיפור יכולת התקשורת, בעיקר לילדים עם לקויות תקשורת.',
  },
  {
    type: 'אבחון הפרעות קשב וריכוז',
    category: 'nan',
    length: 'קצר',
    homework: 'לא',
    description: 'בדיקה לאיתור סימנים ותסמינים של הפרעות קשב.',
  },
  {
    type: 'אבחון לקויי למידה',
    category: 'nan',
    length: 'קצר',
    homework: 'לא',
    description: 'בדיקות לזיהוי לקויות למידה ותכנון תוכניות לימוד מותאמות.',
  },
  {
    type: 'אבחון דידקטי',
    category: 'nan',
    length: 'קצר',
    homework: 'לא',
    description: 'מתמקד בבדיקת כישורים אקדמיים והתאמת תוכניות לימוד.',
  },
  {
    type: 'טיפול פסיכיאטרי',
    category: 'רגשי',
    length: 'ארוך',
    homework: 'לא',
    description: 'מיועד לטיפול בהפרעות נפשיות חמורות, כולל שימוש בתרופות פסיכיאטריות.',
  },
  {
    type: 'טיפול קוגניטיבי התנהגותי (CBT)',
    category: 'רגשי',
    length: 'קצר',
    homework: 'כן',
    description: 'טיפול המתמקד בשינוי דפוסי חשיבה והתנהגות לטיפול בהפרעות חרדה, דיכאון ועוד.',
  },
  {
    type: 'טיפול רגשי בעזרת בעלי חיים',
    category: 'רגשי',
    length: 'nan',
    homework: 'לא',
    description: 'משלב אינטראקציה עם חיות לצורך תמיכה רגשית ופיתוח כישורים חברתיים, מתאים לילדים ומבוגרים.',
  },
  {
    type: 'אבחון פסיכולוגי',
    category: 'nan',
    length: 'קצר',
    homework: 'לא',
    description: 'בדיקה לאבחון מצבים נפשיים והתאמת טיפולים פסיכולוגיים.',
  },
  {
    type: 'מיינדפולנס',
    category: 'רגשי',
    length: 'קצר',
    homework: 'לא',
    description: 'מתמקד בתרגול מיינדפולנס ומדיטציה לשיפור הריכוז, השלווה הנפשית וניהול מתחים.',
  },
  {
    type: 'ניהול לחצים וחוסן אישי',
    category: 'רגשי',
    length: 'קצר',
    homework: 'כן',
    description: 'פותח מיומנויות לניהול לחץ וקידום חוסן נפשי, מתאים לאנשים בעלי עבודות מאומצות ולחוצות.',
  },
  {
    type: 'פוסט טראומה',
    category: 'רגשי',
    length: 'ארוך',
    homework: 'כן',
    description: 'מיועד לטיפול באנשים אחרי טראומה, מתמקד בהתמודדות עם השלכות הטראומה ושחזור התפקוד היומיומי.',
  },
  {
    type: 'NLP',
    category: 'רגשי',
    length: 'קצר',
    homework: 'לא',
    description: 'טכניקת תקשורת ושינוי אישי המתמקדת בשימוש בשפה לשינוי דפוסי חשיבה והתנהגות.',
  },
  {
    type: 'פירוש חלומות',
    category: 'רגשי',
    length: 'קצר',
    homework: 'לא',
    description: 'מסייע למטופלים לפענח ולהבין את משמעויות החלומות שלהם, עלול לסייע בהתמודדות עם רגשות וחוויות בלתי מודעות.',
  },
  {
    type: 'תמציות פרחי באך',
    category: 'רגשי',
    length: 'קצר',
    homework: 'לא',
    description: 'שימוש בתמציות צמחיות לטיפול במצבי רוח, חרדות ומתחים רגשיים.',
  },
  {
    type: 'אבחון נוירופסיכולוגי',
    category: 'nan',
    length: 'קצר',
    homework: 'לא',
    description: 'בדיקות שמאבחנות פגיעות ובעיות בתפקוד המוחי, מיועדות לאבחון מצבים כמו דמנציה, ADHD, ועוד.',
  },
  {
    type: 'nan',
    category: 'nan',
    length: 'nan',
    homework: 'nan',
    description: 'nan',
  },
  {
    type: 'nan',
    category: 'nan',
    length: 'nan',
    homework: 'nan',
    description: 'nan',
  },
  {
    type: 'nan',
    category: 'nan',
    length: 'nan',
    homework: 'nan',
    description: 'nan',
  },
  {
    type: 'nan',
    category: 'nan',
    length: 'nan',
    homework: 'nan',
    description: 'nan',
  },
  {
    type: 'nan',
    category: 'nan',
    length: 'nan',
    homework: 'nan',
    description: 'nan',
  },
  {
    type: 'nan',
    category: 'nan',
    length: 'nan',
    homework: 'nan',
    description: 'nan',
  },
  {
    type: 'nan',
    category: 'nan',
    length: 'nan',
    homework: 'nan',
    description: 'nan',
  },
  {
    type: 'nan',
    category: 'nan',
    length: 'nan',
    homework: 'nan',
    description: 'nan',
  },
  {
    type: 'nan',
    category: 'nan',
    length: 'nan',
    homework: 'nan',
    description: 'nan',
  },
  {
    type: 'nan',
    category: 'nan',
    length: 'nan',
    homework: 'nan',
    description: 'nan',
  },
  {
    type: 'nan',
    category: 'nan',
    length: 'nan',
    homework: 'nan',
    description: 'nan',
  },
  {
    type: 'nan',
    category: 'nan',
    length: 'nan',
    homework: 'nan',
    description: 'nan',
  },
  {
    type: 'nan',
    category: 'nan',
    length: 'nan',
    homework: 'nan',
    description: 'nan',
  },
  {
    type: 'nan',
    category: 'nan',
    length: 'nan',
    homework: 'nan',
    description: 'nan',
  },
  {
    type: 'nan',
    category: 'nan',
    length: 'nan',
    homework: 'nan',
    description: 'nan',
  },
  {
    type: 'nan',
    category: 'nan',
    length: 'nan',
    homework: 'nan',
    description: 'nan',
  },
  {
    type: 'nan',
    category: 'nan',
    length: 'nan',
    homework: 'nan',
    description: 'nan',
  },
  {
    type: 'nan',
    category: 'nan',
    length: 'nan',
    homework: 'nan',
    description: 'nan',
  },
  {
    type: 'nan',
    category: 'nan',
    length: 'nan',
    homework: 'nan',
    description: 'nan',
  },
  {
    type: 'nan',
    category: 'nan',
    length: 'nan',
    homework: 'nan',
    description: 'nan',
  },
  {
    type: 'nan',
    category: 'nan',
    length: 'nan',
    homework: 'nan',
    description: 'nan',
  },
  {
    type: 'nan',
    category: 'nan',
    length: 'nan',
    homework: 'nan',
    description: 'nan',
  },
  {
    type: 'nan',
    category: 'nan',
    length: 'nan',
    homework: 'nan',
    description: 'nan',
  },
  {
    type: 'nan',
    category: 'nan',
    length: 'nan',
    homework: 'nan',
    description: 'nan',
  },
  {
    type: 'nan',
    category: 'nan',
    length: 'nan',
    homework: 'nan',
    description: 'nan',
  },
  {
    type: 'nan',
    category: 'nan',
    length: 'nan',
    homework: 'nan',
    description: 'nan',
  },
  {
    type: 'nan',
    category: 'nan',
    length: 'nan',
    homework: 'nan',
    description: 'nan',
  },
  {
    type: 'nan',
    category: 'nan',
    length: 'nan',
    homework: 'nan',
    description: 'nan',
  },
  {
    type: 'nan',
    category: 'nan',
    length: 'nan',
    homework: 'nan',
    description: 'nan',
  },
  {
    type: 'nan',
    category: 'nan',
    length: 'nan',
    homework: 'nan',
    description: 'nan',
  },
  {
    type: 'nan',
    category: 'nan',
    length: 'nan',
    homework: 'nan',
    description: 'nan',
  },
  {
    type: 'nan',
    category: 'nan',
    length: 'nan',
    homework: 'nan',
    description: 'nan',
  },
  {
    type: 'nan',
    category: 'nan',
    length: 'nan',
    homework: 'nan',
    description: 'nan',
  },
  {
    type: 'nan',
    category: 'nan',
    length: 'nan',
    homework: 'nan',
    description: 'nan',
  },
  {
    type: 'nan',
    category: 'nan',
    length: 'nan',
    homework: 'nan',
    description: 'nan',
  },
  {
    type: 'nan',
    category: 'nan',
    length: 'nan',
    homework: 'nan',
    description: 'nan',
  },
  {
    type: 'nan',
    category: 'nan',
    length: 'nan',
    homework: 'nan',
    description: 'nan',
  },
  {
    type: 'nan',
    category: 'nan',
    length: 'nan',
    homework: 'nan',
    description: 'nan',
  },
  {
    type: 'nan',
    category: 'nan',
    length: 'nan',
    homework: 'nan',
    description: 'nan',
  },
  {
    type: 'nan',
    category: 'nan',
    length: 'nan',
    homework: 'nan',
    description: 'nan',
  },
];

export default treatments;